# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < https://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < https://docs.platformio.org/page/userguide/cmd_ci.html >
#

language: python
python:
  - "2.7"

cache:
  directories:
    - "~/.platformio"

env:
#  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simplest_web_server_esp
#    ENV=huzzah
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simplest_web_server_esp
    ENV=huzzah
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simplest_web_server_esp
    ENV=espwroverkit
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simplest_web_server_native
    ENV=native
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simplest_web_server_native
    ENV=windows_x86
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simple_http_server
    ENV=huzzah
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simple_http_server
    ENV=esp-wrover-kit
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simple_http_server
    ENV=esp-wrover-kit-secure
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simple_http_client
    ENV=huzzah
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simple_http_client
    ENV=esp-wrover-kit
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simple_http_client
    ENV=esp-wrover-kit-secure
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simple_mqtt_client
    ENV=huzzah
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simple_mqtt_client
    ENV=esp-wrover-kit
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/simple_mqtt_client
    ENV=esp-wrover-kit-secure
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/sntp_client
    ENV=huzzah
  - EXAMPLE=$TRAVIS_BUILD_DIR/examples/sntp_client
    ENV=esp-wrover-kit

install:
  - pip install -U platformio
  - platformio update
  - pio lib -g install $TRAVIS_BUILD_DIR

script:
  - cd $EXAMPLE
  - platformio run -e $ENV
