name: Platform IO

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - example: simplest_web_server_esp
          board: huzzah
        - example: simplest_web_server_esp
          board: espwroverkit
        - example: simplest_web_server_native
          board: native
        - example: simplest_web_server_native
          board: windows_x86
        - example: simple_http_server
          board: huzzah
        - example: simple_http_server
          board: esp-wrover-kit
        - example: simple_http_server
          board: esp-wrover-kit-secure
        - example: simple_http_client
          board: huzzah
        - example: simple_http_client
          board: esp-wrover-kit
        - example: simple_http_client
          board: esp-wrover-kit-secure
        - example: simple_mqtt_client
          board: huzzah
        - example: simple_mqtt_client
          board: esp-wrover-kit
        - example: simple_mqtt_client
          board: esp-wrover-kit-secure
        - example: websocket_chat
          board: huzzah
        - example: websocket_chat
          board: esp-wrover-kit
        - example: websocket_chat
          board: esp-wrover-kit-secure
        - example: esp_ota_http_server
          board: esp-wrover-kit
        - example: esp_ota_http_server
          board: esp-wrover-kit-secure
        - example: esp_ota_http_server
          board: esp-wrover-kit-auth
        - example: sntp_client
          board: huzzah
        - example: sntp_client
          board: esp-wrover-kit

    runs-on: ubuntu-latest
    name: Build ${{ matrix.example }}-${{ matrix.board }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install Platform IO
        run:
          |
          pip install -U platformio
          platformio update

      - name: Install Checked out ArduinoMongoose
        run:
          pio lib -g install $GITHUB_WORKSPACE

      - name: Build example 
        run:
          |
          cd examples/${{ matrix.example }}
          pio run -e ${{ matrix.board }}
